name: social_app
description: "U-Axis Social Media Application"
publish_to: 'none'
version: 1.0.0+1

environment:
  sdk: '>=3.0.0 <4.0.0'

dependencies:
  flutter:
    sdk: flutter
  flutter_localizations:
    sdk: flutter
  cupertino_icons: ^1.0.8
  flutter_riverpod: ^2.6.1
  go_router: ^14.7.1
  equatable: ^2.0.7
  intl: ^0.20.2
  sqflite: ^2.4.1
  flutter_secure_storage: ^9.2.4
  flutter_local_notifications: ^18.0.1
  path: ^1.9.1
  cryptography: ^2.7.0
  uuid: ^4.5.1
  flutter_svg: ^2.2.3
  font_awesome_flutter: ^10.12.0
  dio: ^5.9.1
  google_sign_in: ^6.2.2
  http: ^1.2.0
  shared_preferences: ^2.2.2

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^5.0.0

flutter:
  uses-material-design: true
  generate: true
  assets:
    - assets/icons/
